apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfghjkl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfghjkl
  template:
    metadata:
      labels:
        app: dfghjkl
    spec:
      containers:
      - image: okteto.dev/dfghjkl:latest
        name: dfghjkl
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "$ProxySite"
        - name: Vless_UUID
          value: "b4dba4af-d5e4-4ce4-b366-72e2a9b599c6"
        - name: Vless_Path
          value: "$Vless_Path"
        - name: Vmess_UUID
          value: "b4dba4af-d5e4-4ce4-b366-72e2a9b599c6"
        - name: Vmess_Path
          value: "$Vmess_Path"
        - name: Share_Path
          value: "$Share_Path"
